site_name: matrix.py
site_description: A simple, developer-friendly library to create powerful Matrix bots.
site_url: https://matrixpy.code-society.xyz/
theme:
  name: material
  palette:
    - media: (prefers-color-scheme)
      toggle:
        icon: material/lightbulb-auto
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: black
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference
  features:
    - content.code.annotate
    - content.code.copy
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/matrixpy-white.svg
  favicon: img/favicon.svg
  language: en
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_if_no_docstring: true
            inherited_members: false
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters:
            - '!^_'
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Reference:
      - Bot: reference/bot.md
      - Checks: reference/checks.md
      - Command: reference/command.md
      - Config: reference/config.md
      - Content: reference/content.md
      - Context: reference/context.md
      - Errors: reference/errors.md
      - Extension: reference/extension.md
      - Group: reference/group.md
      - Message: reference/message.md
      - Protocols: reference/protocols.md
      - Registry: reference/registry.md
      - Room: reference/room.md
      - Scheduler: reference/scheduler.md
      - Types: reference/types.md